### ISSUE TITLE
Most sites matched to Andrew Napolitano

### ISSUE THREAD

**Issue by erikreagan** [TheUnlocked/Bias-Finder#7]
Firefox 77.0.1
Bias Finder 1.0.2

I noticed most sites are matching to **Andrew Napolitano**. I scanned through the [AllSides json feed being used](https://github.com/TheUnlocked/Bias-Finder/blob/master/Extension/background.js#L42) and noticed that this is the first node where there is an empty string value for `url`. 

http://drop.focuslabllc.com/XwDPr3

I'm wondering if the json feed itself has changed in a way that has broken this Firefox plugin. I love AllSides and would **really** love to use this plugin. For now, though, this bug is a show stopper unfortunately. So I wanted to report what I found.

Thanks!

**Comment by TheUnlocked** [comment]
I thought I fixed this bug but maybe I never pushed it to Firefox. Thank you for bringing this to my attention. The fixed version should be available soon.

**Comment by erikreagan** [comment]
You know, I thought I saw a conditional checking for that in the js. Good to know. I look forward to the update. Thanks!
